Datum einfügen
HuSchKa2020/Studienarbeit pull request #38
Opened 2021-04-13 10:17 UTC by derSchumann

2021-04-13 10:42 UTC, Wilhelm-kaden commented
Ihr müsst zuerst die SQL-Befehle ausführen. Danach haben alle bereits erstellte Fehler ein Erstelldatum. Danach könnt ihr mit der GET-Methode das ErstellDatum abfragen.

im Frontend habe ich mit Max zusammen das Datum bei der Fehlersuche hinzugefügt

2021-04-14 14:34 UTC, Jan1208 requested changes
- datum- spalte auch in der tables.sql hinzufügen
 - Zeit ist nicht deutsche Zeit, wahrscheinlich ist es GMT. um 16:30 stand am Fehler 12:30
 - 
sonst is Jut

2021-04-14 15:15 UTC, Wilhelm-kaden commented
Ich habe die Table.sql angepasst und ihr müsst noch den Befehl ausführen, um bei euch die richtige Zeitzone in der Datenbank zu hinterlegen. Diesen findet ihr in Datum.sql. Danach müsste alles übereinstimmen

2021-04-15 07:22 UTC, Jan1208 approved these changes
zeit ist noch nicht richtig, merge das einfach und mach ne karte dazu

2021-04-15 09:48 UTC, merged