34--Dropdownliste
HuSchKa2020/Studienarbeit pull request #40
Opened 2021-04-14 14:58 UTC by Wilhelm-kaden

Im Layout zum erstellen eines Fehler sind nun die Dropdownlisten vorhanden und funktionieren einwandfrei. Mir ist allerdings aufgefallen, das bei der Fehlersuche für die Software nur die ID ausgegeben wird. Ich würde vorschlagen, das wir das zu einem späteren Zeitpunkt anpassen bzw. wenn ich das noch schnell machen soll müsst ihr es sagen.

2021-04-15 07:29 UTC, Jan1208 requested changes
sieht schick aus, aber noch bissle dynamische machen in dem du dir die infos mit nem fetch vom server holst

2021-04-15 07:29 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +              <div className="field" id="AuswirkungContainer">
auskommentierter code kann weg

2021-04-15 07:29 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +          <option value="1">Wilhelm Kaden</option>
hier als optionen bitte die anwender von der route GET /anwender, die war ja extra dafür gedacht

2021-04-15 07:29 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +          <option value="1">S/4 Hana</option>
hier als optionen bitte die Softwares von der route GET /software, die war ja extra dafür gedacht

2021-04-15 12:53 UTC, derSchumann commented
Bitte die dropdown abrunden - 20px
und standardmäßig leer

2021-04-19 11:51 UTC, Wilhelm-kaden commented
so jetzt sollten in den Dropdownlisten (Softwareid und Anwenderid). immer die entsprechenden Daten aus der Datenbank angezeigt werden.

2021-04-19 12:37 UTC, derSchumann reviewed
klappt einwandfrei
würde aber "offen" statt "nicht behoben" nehme bei status.

2021-04-19 12:48 UTC, Jan1208 requested changes

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +    var url = 'http://localhost:5000/software';
url bitte in den constants

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +    var url = 'http://localhost:5000/software';
so funktioniert das nur für localhost

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +    var url = 'http://localhost:5000/anwender';
ebenso url in die constants

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +      setSoftware([]);
diese zeile kann weg, software ist ja durch zeile 22 automatsch ein leeres array

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +      setSoftware([]);
auch das console.log muss nicht sein, da guckt ja kein anwender rein

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +    console.log(setAnwender);
console.log kann auch weg

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +      console.log("keine software gefunden");
console.log kann auch weg

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +      setAnwender([]);
gleiches wie bei der software

2021-04-19 12:48 UTC, Jan1208 commented on client/src/components/FehlerErstellen.js
> +      {anwender.map((anwenders) =>(
"anwenders", da reicht auch nur anwender, klingt sonst komisch

2021-04-20 12:45 UTC, merged